/*Given an array arr[] of N positive elements.
The task is to find the Maximum AND Value generated by any pair(arri, arrj) from the array such that i != j.*/




int maxAND (int arr[], int n)
    {
        int max = 0;
        for(int i= 0; i<n; i++)
        {
            if(arr[i]>max)
            max = arr[i];
        }
        int p = 1<<(int)log2(max);
        int res = 0;
        
        while(p)
        {
            int count = 0;
            for(int i = 0; i<n ; i++)
            {
                if((arr[i]&(p|res)) == (p|res))
                    count++;
                
            }
            if(count>1)
            {
                res = res ^ p;
            }
            p = p>>1;
        }
        return res;
    }
